apiVersion: networking.k8s.io/v1
   
kind: Ingress
   
metadata:
  name: sampleapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:   
  rules:   
    - host: akupriyanov.dacdevops.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sampleapp-service
                port:
                  name: http